### ISSUE TITLE
iota-ipm showing wrong port numbers

### ISSUE THREAD

**Issue by rnagler** [akashgoswami/ipm#45]
My node is behind a router and external ports are transferred to internal ports.
After some time my tcp neighbor sees in iota-pm instead of my external url tcp://x.y.com:13095 my internal port number, tcp://x.y.com:15777. I assume, that the internal portnumber is transported in some transactions and finds its way to the iota-ipm. The effect is letal, because before a restart the operator will save the list of neighbors and copy them into his iota.ini file. After restart the wrong external portnumbers prohibit further communication...

**Comment by ixidion** [comment]
To get it clear: You are operating the node behind a NAT?

**Comment by rnagler** [comment]
yes, because my company network runs a lot of different services, so you have to find free external ports.  The same may be true for datacenters. There is no problem in running iri - its only that the ipm running on my neighbor's node displays after "some time" my internal port numbers instead of my external port numbers.

**Comment by akashgoswami** [comment]
Hi,

IOTA PM retrieves the list of neighbors from IRI via the APIs. If the ports are changed, it is due to IRI reporting incorrect ports. Could you please raise this issue with IRI repo instead? It would also be helpful to get a curl output in this situation from following API 
https://iota.readme.io/reference#getneighborsactivity

**Comment by rnagler** [comment]
raised with iri repo, see: https://github.com/iotaledger/iri/issues/382
